<?php
declare(strict_types=1);

use App\Services\ProjectRevisionService;
use PHPUnit\Framework\TestCase;

final class ApiV2ProjectSynchronizationTest extends TestCase
{
    private PDO $pdo;private array $headers=['source'=>'123e4567-e89b-42d3-a456-426614174000','application'=>'223e4567-e89b-42d3-a456-426614174000','epoch'=>'323e4567-e89b-42d3-a456-426614174000'];
    protected function setUp():void
    {
        if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped('pdo_sqlite required');$root=dirname(__DIR__,2);require_once $root.'/src/utils/api_v2_project_sync.php';require_once $root.'/src/utils/api_v2_project_release_safety.php';
        $this->pdo=new PDO('sqlite::memory:');$this->pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$this->pdo->exec('PRAGMA foreign_keys=ON');
        $this->pdo->exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,filename TEXT,checksum TEXT);CREATE TABLE api_keys(id INTEGER PRIMARY KEY,api_v2_application_id INTEGER,revoked_at TEXT);CREATE TABLE api_v2_applications(id INTEGER PRIMARY KEY,application_id TEXT);CREATE TABLE api_v2_history_identity(singleton INTEGER PRIMARY KEY,source_instance_id TEXT,history_epoch TEXT);CREATE TABLE api_v2_project_authorization_state(application_pk INTEGER PRIMARY KEY,authorization_generation INTEGER,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE users(id INTEGER PRIMARY KEY);
        CREATE TABLE organizations(id INTEGER PRIMARY KEY,public_id TEXT,name TEXT,general_email TEXT,general_phone TEXT,address_line1 TEXT,address_line2 TEXT,city TEXT,state TEXT,postal_code TEXT,country TEXT);CREATE TABLE clients(id INTEGER PRIMARY KEY,public_id TEXT,name TEXT,email TEXT,phone TEXT,client_type TEXT,organization_id INTEGER,address_line1 TEXT,address_line2 TEXT,city TEXT,state TEXT,postal_code TEXT,country TEXT);
        CREATE TABLE api_v2_directory_resource_state(resource_type TEXT,public_id TEXT,revision INTEGER,projection_sha256 TEXT,present INTEGER,PRIMARY KEY(resource_type,public_id));CREATE TABLE api_v2_directory_external_bindings(application_pk INTEGER,resource_type TEXT,external_id TEXT,public_id TEXT,resource_revision INTEGER,resource_projection_sha256 TEXT,status TEXT,PRIMARY KEY(application_pk,resource_type,external_id));
        CREATE TABLE projects(id INTEGER PRIMARY KEY AUTOINCREMENT,public_id TEXT UNIQUE,client_id INTEGER,organization_id INTEGER,department_id INTEGER,name TEXT,description TEXT,status TEXT,completed_at TEXT,archived_at TEXT,portal_publish_enabled INTEGER DEFAULT 1,public_project_enabled INTEGER DEFAULT 0,revision INTEGER DEFAULT 1,estimated_start TEXT,estimated_end TEXT,source_version TEXT,invoice_billing_period TEXT,project_invoice_auto_email INTEGER,created_by INTEGER,updated_at TEXT);CREATE TABLE project_retention_guards(project_public_id TEXT PRIMARY KEY);CREATE TABLE project_changes(project_public_id TEXT,revision INTEGER,action_name TEXT,projection_sha256 TEXT,application_pk INTEGER,command_id TEXT,actor_user_id INTEGER,changed_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(project_public_id,revision));
        CREATE TABLE api_v2_project_external_bindings(application_pk INTEGER,external_id TEXT,project_public_id TEXT,project_revision INTEGER,project_projection_sha256 TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(application_pk,external_id),UNIQUE(application_pk,project_public_id));CREATE TABLE api_v2_project_command_receipts(application_pk INTEGER,history_epoch TEXT,command_id TEXT,command_type TEXT,request_sha256 TEXT,external_id TEXT,project_public_id TEXT,expected_revision INTEGER,expected_prior_revision INTEGER,expected_projection_sha256 TEXT,expected_authorization_generation INTEGER,result_revision INTEGER,result_projection_sha256 TEXT,result_authorization_generation INTEGER,result_portal_publish_enabled INTEGER,result_public_project_enabled INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(application_pk,history_epoch,command_id));CREATE TABLE api_v2_project_backfill_attestations(attestation_sha256 TEXT PRIMARY KEY,attestation_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
        CREATE TABLE app_config(organization_id INTEGER,config_key TEXT,config_value TEXT);CREATE TABLE project_service_locations(id INTEGER PRIMARY KEY,project_id INTEGER,service_location_id INTEGER,is_default INTEGER);CREATE TABLE schedule_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,project_id INTEGER,job_id INTEGER,service_location_id INTEGER,title TEXT,starts_at TEXT,ends_at TEXT,timezone TEXT,status TEXT,source_type TEXT,source_id INTEGER,created_by INTEGER,UNIQUE(source_type,source_id),FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL);
        CREATE TABLE portal_integration_profiles(id INTEGER PRIMARY KEY,enabled INTEGER,portal_projection_enabled INTEGER,delivery_enabled INTEGER);CREATE TABLE portal_v2_workspaces(id INTEGER PRIMARY KEY,public_id TEXT,root_type TEXT,root_public_id TEXT,display_name TEXT,source_version TEXT,active INTEGER);CREATE TABLE portal_integration_profile_workspaces(profile_id INTEGER,workspace_id INTEGER,active INTEGER);CREATE TABLE portal_projection_state(integration_profile_id INTEGER,workspace_public_id TEXT,source_generation TEXT,source_sequence INTEGER,last_snapshot_hash TEXT,PRIMARY KEY(integration_profile_id,workspace_public_id));CREATE TABLE portal_projection_outbox(id INTEGER PRIMARY KEY,delivery_id TEXT,delivered_at TEXT,payload_json TEXT);
        INSERT INTO api_keys VALUES(7,3,NULL);INSERT INTO api_v2_applications VALUES(3,'223e4567-e89b-42d3-a456-426614174000');INSERT INTO api_v2_history_identity VALUES(1,'123e4567-e89b-42d3-a456-426614174000','323e4567-e89b-42d3-a456-426614174000');INSERT INTO api_v2_project_authorization_state(application_pk,authorization_generation) VALUES(3,0);INSERT INTO app_config VALUES(0,'portal_authoritative_hooks_enabled','1');INSERT INTO organizations VALUES(10,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','Org',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);INSERT INTO clients VALUES(11,'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','Client',NULL,NULL,'business',10,NULL,NULL,NULL,NULL,NULL,NULL);
        INSERT INTO portal_integration_profiles VALUES(9,1,1,1);INSERT INTO portal_v2_workspaces VALUES(8,'workspace-existing','organization','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','Org','workspace-v1',1);INSERT INTO portal_integration_profile_workspaces VALUES(9,8,1);INSERT INTO portal_projection_state VALUES(9,'workspace-existing','generation-existing',4,'snapshot-existing');INSERT INTO portal_projection_outbox VALUES(6,'delivery-existing','2026-09-01','{\"sentinel\":true}');");
        $migrationPath=$root.'/database/migrations/0102_api_v2_project_synchronization.sql';$this->pdo->prepare('INSERT INTO schema_migrations VALUES(102,?,?)')->execute(['0102_api_v2_project_synchronization.sql',hash_file('sha256',$migrationPath)]);
        foreach([['organization',10,'org-ext'],['client',11,'client-ext']]as[$type,$id,$external]){$table=$type==='organization'?'organizations':'clients';$row=$this->pdo->query("SELECT * FROM $table WHERE id=$id")->fetch(PDO::FETCH_ASSOC);$hash=api_v2_directory_projection_hash($type,$row);$public=$row['public_id'];$this->pdo->prepare('INSERT INTO api_v2_directory_resource_state VALUES(?,?,1,?,1)')->execute([$type,$public,$hash]);$this->pdo->prepare("INSERT INTO api_v2_directory_external_bindings VALUES(3,?,?,?,1,?,'active')")->execute([$type,$external,$public,$hash]);}
    }
    private function relation(string$type):array{$public=$type==='organization'?str_repeat('a',32):str_repeat('b',32);$state=$this->pdo->prepare('SELECT projection_sha256 FROM api_v2_directory_resource_state WHERE resource_type=?');$state->execute([$type]);return['externalId'=>$type==='organization'?'org-ext':'client-ext','expectedPublicId'=>$public,'expectedRevision'=>'1','expectedProjectionSha256'=>$state->fetchColumn()];}
    private function createCommand(string $commandId,string $externalId='project-conflict'):array{return['commandId'=>$commandId,'externalId'=>$externalId,'expectedAuthorizationGeneration'=>'0','project'=>['name'=>'Shared name','description'=>'Safe scope','estimatedStart'=>'2026-09-01','estimatedEnd'=>'2026-09-30'],'organization'=>$this->relation('organization'),'client'=>$this->relation('client')];}
    private function assertSyncConflict(array $outcome,string $code,string $requestId,bool $verifiedIdentity=true):void
    {
        self::assertSame(409,$outcome['status']);self::assertSame($verifiedIdentity?['apiVersion','sourceInstanceId','applicationId','historyEpoch','requestId','error']:['apiVersion','requestId','error'],array_keys($outcome['payload']));self::assertSame(['code'=>$code],$outcome['payload']['error']);self::assertSame($requestId,$outcome['payload']['requestId']);
        $encoded=json_encode($outcome['payload'],JSON_THROW_ON_ERROR);foreach(['project-conflict','Shared name','Safe scope','org-ext','client-ext']as$privateValue)self::assertStringNotContainsString($privateValue,$encoded);self::assertArrayNotHasKey('result',$outcome['payload']);
    }
    private function portalState():array{return['workspace'=>$this->pdo->query('SELECT * FROM portal_v2_workspaces ORDER BY id')->fetchAll(PDO::FETCH_ASSOC),'projection'=>$this->pdo->query('SELECT * FROM portal_projection_state ORDER BY integration_profile_id,workspace_public_id')->fetchAll(PDO::FETCH_ASSOC),'outbox'=>$this->pdo->query('SELECT * FROM portal_projection_outbox ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)];}
    private function assertPortalUnchanged(array$before):void{self::assertSame($before,$this->portalState(),'Project synchronization must be portal/delivery neutral.');}
    public function testCreateUpdateNoOpBindAndRefreshNeverProjectOrDeliver():void
    {
        $portal=$this->portalState();$create=['commandId'=>'423e4567-e89b-42d3-a456-426614174000','externalId'=>'project-ext','expectedAuthorizationGeneration'=>'0','project'=>['name'=>'Shared name','description'=>'Safe scope','estimatedStart'=>'2026-09-01','estimatedEnd'=>'2026-09-30'],'organization'=>$this->relation('organization'),'client'=>$this->relation('client')];
        $out=api_v2_project_sync_write($this->pdo,'create',$create,7,$this->headers,'r1');self::assertSame(201,$out['status']);self::assertSame('1',$out['payload']['result']['authorizationGeneration']);self::assertSame(['portalPublished'=>false,'publicLinkEnabled'=>false],$out['payload']['result']['presentation']);self::assertSame(1,(int)$this->pdo->query('SELECT COUNT(*) FROM schedule_entries')->fetchColumn());self::assertNull($this->pdo->query('SELECT created_by FROM schedule_entries')->fetchColumn());self::assertSame(1,(int)$this->pdo->query('SELECT revision FROM projects')->fetchColumn());$createVersion=(string)$this->pdo->query('SELECT source_version FROM projects')->fetchColumn();self::assertMatchesRegularExpression('/^v-[0-9a-f]{32}$/',$createVersion);$this->assertPortalUnchanged($portal);
        self::assertTrue(api_v2_project_sync_write($this->pdo,'create',$create,7,$this->headers,'r2')['payload']['replayed']);$this->assertPortalUnchanged($portal);$changed=$create;$changed['project']['name']='Other';self::assertSame(409,api_v2_project_sync_write($this->pdo,'create',$changed,7,$this->headers,'r3')['status']);
        $resource=$out['payload']['result']['resource'];$update=['commandId'=>'523e4567-e89b-42d3-a456-426614174000','externalId'=>'project-ext','expectedRevision'=>$resource['revision'],'expectedProjectionSha256'=>$resource['projectionSha256'],'expectedAuthorizationGeneration'=>'1','project'=>['name'=>'Shared name','description'=>'Updated','estimatedStart'=>'2026-09-01','estimatedEnd'=>'2026-10-01']];$updated=api_v2_project_sync_write($this->pdo,'update',$update,7,$this->headers,'r4');self::assertSame('2',$updated['payload']['result']['resource']['revision']);$updateVersion=(string)$this->pdo->query('SELECT source_version FROM projects')->fetchColumn();self::assertNotSame($createVersion,$updateVersion);$this->assertPortalUnchanged($portal);
        $unchanged=$update;$unchanged['commandId']='533e4567-e89b-42d3-a456-426614174000';$unchanged['expectedRevision']='2';$unchanged['expectedProjectionSha256']=$updated['payload']['result']['resource']['projectionSha256'];$noOp=api_v2_project_sync_write($this->pdo,'update',$unchanged,7,$this->headers,'r5');self::assertSame('2',$noOp['payload']['result']['resource']['revision']);self::assertSame($updateVersion,$this->pdo->query('SELECT source_version FROM projects')->fetchColumn());self::assertSame(2,(int)$this->pdo->query('SELECT COUNT(*) FROM project_changes')->fetchColumn());$this->assertPortalUnchanged($portal);
        $this->pdo->exec("INSERT INTO projects(public_id,organization_id,name,status,portal_publish_enabled,public_project_enabled,revision,source_version,invoice_billing_period,project_invoice_auto_email) VALUES('cccccccccccccccccccccccccccccccc',10,'Browser project','not_started',1,0,1,'browser-v1','per_invoice',0)");$browserId=(int)$this->pdo->lastInsertId();$this->pdo->beginTransaction();$browser=(new ProjectRevisionService($this->pdo))->initialize($browserId,'baseline');$this->pdo->commit();$bind=['commandId'=>'543e4567-e89b-42d3-a456-426614174000','externalId'=>'browser-project-ext','expectedPublicId'=>str_repeat('c',32),'expectedRevision'=>'1','expectedProjectionSha256'=>ProjectRevisionService::projectionHash($browser),'expectedAuthorizationGeneration'=>'1'];$bound=api_v2_project_sync_write($this->pdo,'bind',$bind,7,$this->headers,'r6');self::assertSame(200,$bound['status']);self::assertSame('2',$bound['payload']['result']['authorizationGeneration']);$this->assertPortalUnchanged($portal);
        $inventory=api_v2_project_inventory_read($this->pdo,null,10,7,$this->headers,'r7');self::assertSame(200,$inventory['status']);self::assertSame(['apiVersion','sourceInstanceId','applicationId','historyEpoch','requestId','authorizationGeneration','projects','nextCursor'],array_keys($inventory['payload']));self::assertCount(2,$inventory['payload']['projects']);self::assertSame(['externalId','publicId','revision','projectionSha256','status','archived'],array_keys($inventory['payload']['projects'][0]));self::assertArrayNotHasKey('budget',$inventory['payload']['projects'][0]);$id=(int)$this->pdo->query("SELECT id FROM projects WHERE public_id='".$resource['publicId']."'")->fetchColumn();$this->pdo->beginTransaction();$this->pdo->exec("UPDATE projects SET name='Browser edit' WHERE id=$id");$live=(new ProjectRevisionService($this->pdo))->advance($id,'update');$this->pdo->commit();
        $boundedPage=api_v2_project_inventory_read($this->pdo,null,1,7,$this->headers,'bounded-page');self::assertSame(200,$boundedPage['status']);self::assertSame(['browser-project-ext'],array_column($boundedPage['payload']['projects'],'externalId'));self::assertSame('browser-project-ext',$boundedPage['payload']['nextCursor']);
        $selectedStale=api_v2_project_inventory_read($this->pdo,$boundedPage['payload']['nextCursor'],1,7,$this->headers,'selected-stale');self::assertSame(409,$selectedStale['status']);self::assertSame(['apiVersion'=>'2','sourceInstanceId'=>$this->headers['source'],'applicationId'=>$this->headers['application'],'historyEpoch'=>$this->headers['epoch'],'requestId'=>'selected-stale','error'=>['code'=>'binding_stale','externalId'=>'project-ext']],$selectedStale['payload']);
        $staleInventory=api_v2_project_inventory_read($this->pdo,null,10,7,$this->headers,'stale-inventory');self::assertSame(409,$staleInventory['status']);self::assertSame([
            'apiVersion'=>'2','sourceInstanceId'=>$this->headers['source'],'applicationId'=>$this->headers['application'],'historyEpoch'=>$this->headers['epoch'],'requestId'=>'stale-inventory','error'=>['code'=>'binding_stale','externalId'=>'project-ext'],
        ],$staleInventory['payload']);
        $stale=api_v2_project_binding_status_read($this->pdo,'project-ext',7,$this->headers,'r8');self::assertSame(409,$stale['status']);self::assertSame([
            'apiVersion'=>'2','sourceInstanceId'=>$this->headers['source'],'applicationId'=>$this->headers['application'],'historyEpoch'=>$this->headers['epoch'],'requestId'=>'r8','error'=>['code'=>'binding_stale'],'authorizationGeneration'=>'2',
            'binding'=>['externalId'=>'project-ext','publicId'=>$resource['publicId'],'revision'=>'2'],
            'resource'=>['revision'=>'3','projectionSha256'=>ProjectRevisionService::projectionHash($live)],
        ],$stale['payload']);
        $hash=ProjectRevisionService::projectionHash($live);$refresh=['commandId'=>'623e4567-e89b-42d3-a456-426614174000','externalId'=>'project-ext','expectedPublicId'=>$resource['publicId'],'expectedPriorRevision'=>'2','expectedRevision'=>'3','expectedProjectionSha256'=>$hash,'expectedAuthorizationGeneration'=>'2'];$refreshed=api_v2_project_sync_write($this->pdo,'refresh',$refresh,7,$this->headers,'r9');self::assertSame('3',$refreshed['payload']['result']['authorizationGeneration']);$current=api_v2_project_binding_status_read($this->pdo,'project-ext',7,$this->headers,'r10');self::assertSame(200,$current['status']);self::assertSame(['apiVersion','sourceInstanceId','applicationId','historyEpoch','requestId','authorizationGeneration','binding','resource'],array_keys($current['payload']));self::assertSame(['externalId'=>'project-ext','publicId'=>$resource['publicId'],'createdAt'=>$current['payload']['binding']['createdAt'],'updatedAt'=>$current['payload']['binding']['updatedAt']],$current['payload']['binding']);self::assertSame(['revision'=>'3','projectionSha256'=>$hash,'status'=>'not_started','archived'=>false],$current['payload']['resource']);self::assertArrayNotHasKey('error',$current['payload']);$this->assertPortalUnchanged($portal);
    }
    public function testSyncConflictsUseStableNonDisclosingReasons():void
    {
        $create=$this->createCommand('423e4567-e89b-42d3-a456-426614174000');$wrongIdentity=$this->headers;$wrongIdentity['application']='423e4567-e89b-42d3-a456-426614174000';$this->assertSyncConflict(api_v2_project_sync_write($this->pdo,'create',$create,7,$wrongIdentity,'identity'),'identity_conflict','identity',false);
        $staleGeneration=$this->createCommand('433e4567-e89b-42d3-a456-426614174000');$staleGeneration['expectedAuthorizationGeneration']='1';$this->assertSyncConflict(api_v2_project_sync_write($this->pdo,'create',$staleGeneration,7,$this->headers,'generation'),'authorization_generation_conflict','generation');
        $badProof=$this->createCommand('443e4567-e89b-42d3-a456-426614174000');$badProof['organization']['expectedRevision']='2';$this->assertSyncConflict(api_v2_project_sync_write($this->pdo,'create',$badProof,7,$this->headers,'relationship'),'relationship_proof_conflict','relationship');
        self::assertSame(201,api_v2_project_sync_write($this->pdo,'create',$create,7,$this->headers,'created')['status']);$changed=$create;$changed['project']['name']='Changed name';$this->assertSyncConflict(api_v2_project_sync_write($this->pdo,'create',$changed,7,$this->headers,'command-id'),'command_id_conflict','command-id');
        $duplicateBinding=$this->createCommand('463e4567-e89b-42d3-a456-426614174000');$duplicateBinding['expectedAuthorizationGeneration']='1';$this->assertSyncConflict(api_v2_project_sync_write($this->pdo,'create',$duplicateBinding,7,$this->headers,'binding'),'external_binding_conflict','binding');
        $this->pdo->exec("CREATE TRIGGER reject_project_sync_receipt BEFORE INSERT ON api_v2_project_command_receipts BEGIN SELECT RAISE(ABORT, 'private constraint detail'); END");$databaseConstraint=$this->createCommand('473e4567-e89b-42d3-a456-426614174000','other-project-conflict');$databaseConstraint['expectedAuthorizationGeneration']='1';$this->assertSyncConflict(api_v2_project_sync_write($this->pdo,'create',$databaseConstraint,7,$this->headers,'database'),'database_constraint_conflict','database');self::assertSame(1,(int)$this->pdo->query('SELECT COUNT(*) FROM projects')->fetchColumn());
    }
    public function testBindingStatusRecoveryDoesNotExposeUnboundOrUnverifiedProjects():void
    {
        $this->pdo->exec("INSERT INTO projects(public_id,organization_id,name,status,portal_publish_enabled,public_project_enabled,revision,source_version,invoice_billing_period,project_invoice_auto_email) VALUES('dddddddddddddddddddddddddddddddd',10,'Unbound project','not_started',0,0,1,'browser-v1','per_invoice',0)");$unboundId=(int)$this->pdo->lastInsertId();$this->pdo->beginTransaction();(new ProjectRevisionService($this->pdo))->initialize($unboundId,'baseline');$this->pdo->commit();
        self::assertSame(['status'=>404],api_v2_project_binding_status_read($this->pdo,'not-bound',7,$this->headers,'unbound'));
        $bind=['commandId'=>'643e4567-e89b-42d3-a456-426614174000','externalId'=>'bound','expectedPublicId'=>str_repeat('d',32),'expectedRevision'=>'1','expectedProjectionSha256'=>(string)$this->pdo->query("SELECT projection_sha256 FROM project_changes WHERE project_public_id='dddddddddddddddddddddddddddddddd'")->fetchColumn(),'expectedAuthorizationGeneration'=>'0'];
        self::assertSame(200,api_v2_project_sync_write($this->pdo,'bind',$bind,7,$this->headers,'bind')['status']);
        $this->pdo->exec("DELETE FROM project_changes WHERE project_public_id='dddddddddddddddddddddddddddddddd'");
        self::assertSame(['status'=>409],api_v2_project_binding_status_read($this->pdo,'bound',7,$this->headers,'corrupt'));
        $wrongHeaders=$this->headers;$wrongHeaders['application']='423e4567-e89b-42d3-a456-426614174000';
        self::assertSame(['status'=>409],api_v2_project_binding_status_read($this->pdo,'bound',7,$wrongHeaders,'wrong-identity'));
    }
    public function testBindingRecoveryRejectsHashOnlyDriftAndBindingAheadOfLiveHistory():void
    {
        $this->pdo->exec("INSERT INTO projects(public_id,organization_id,name,status,portal_publish_enabled,public_project_enabled,revision,source_version,invoice_billing_period,project_invoice_auto_email) VALUES('eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',10,'Bound project','not_started',0,0,1,'browser-v1','per_invoice',0)");$id=(int)$this->pdo->lastInsertId();$this->pdo->beginTransaction();$project=(new ProjectRevisionService($this->pdo))->initialize($id,'baseline');$this->pdo->commit();
        $originalHash=ProjectRevisionService::projectionHash($project);$bind=['commandId'=>'653e4567-e89b-42d3-a456-426614174000','externalId'=>'unsafe','expectedPublicId'=>str_repeat('e',32),'expectedRevision'=>'1','expectedProjectionSha256'=>$originalHash,'expectedAuthorizationGeneration'=>'0'];self::assertSame(200,api_v2_project_sync_write($this->pdo,'bind',$bind,7,$this->headers,'bind')['status']);
        $this->pdo->exec("UPDATE api_v2_project_external_bindings SET project_projection_sha256='".str_repeat('f',64)."' WHERE external_id='unsafe'");
        self::assertSame(['status'=>409],api_v2_project_binding_status_read($this->pdo,'unsafe',7,$this->headers,'equal-hash-drift'));self::assertSame(['status'=>409],api_v2_project_inventory_read($this->pdo,null,10,7,$this->headers,'equal-hash-inventory'));
        $this->pdo->beginTransaction();$this->pdo->exec("UPDATE projects SET name='New live revision' WHERE id=$id");(new ProjectRevisionService($this->pdo))->advance($id,'update');$this->pdo->commit();$this->pdo->exec("UPDATE api_v2_project_external_bindings SET project_revision=1,project_projection_sha256='".str_repeat('f',64)."' WHERE external_id='unsafe'");
        self::assertSame(['status'=>409],api_v2_project_binding_status_read($this->pdo,'unsafe',7,$this->headers,'old-revision-wrong-hash'));self::assertSame(['status'=>409],api_v2_project_inventory_read($this->pdo,null,10,7,$this->headers,'old-revision-wrong-hash-inventory'));
        $this->pdo->exec("UPDATE api_v2_project_external_bindings SET project_revision=3,project_projection_sha256='$originalHash' WHERE external_id='unsafe'");
        self::assertSame(['status'=>409],api_v2_project_binding_status_read($this->pdo,'unsafe',7,$this->headers,'binding-ahead'));self::assertSame(['status'=>409],api_v2_project_inventory_read($this->pdo,null,10,7,$this->headers,'ahead-inventory'));
    }
    public function testBindingRecoveryEvidenceIsFencedAgainstGenerationAndLiveRevisionRaces():void
    {
        $this->pdo->exec("INSERT INTO projects(public_id,organization_id,name,status,portal_publish_enabled,public_project_enabled,revision,source_version,invoice_billing_period,project_invoice_auto_email) VALUES('ffffffffffffffffffffffffffffffff',10,'Race project','not_started',0,0,1,'browser-v1','per_invoice',0)");$id=(int)$this->pdo->lastInsertId();$this->pdo->beginTransaction();$project=(new ProjectRevisionService($this->pdo))->initialize($id,'baseline');$this->pdo->commit();
        $bind=['commandId'=>'663e4567-e89b-42d3-a456-426614174000','externalId'=>'race','expectedPublicId'=>str_repeat('f',32),'expectedRevision'=>'1','expectedProjectionSha256'=>ProjectRevisionService::projectionHash($project),'expectedAuthorizationGeneration'=>'0'];self::assertSame(200,api_v2_project_sync_write($this->pdo,'bind',$bind,7,$this->headers,'bind')['status']);
        $this->pdo->beginTransaction();$this->pdo->exec("UPDATE projects SET name='Browser edit one' WHERE id=$id");$live=(new ProjectRevisionService($this->pdo))->advance($id,'update');$this->pdo->commit();$status=api_v2_project_binding_status_read($this->pdo,'race',7,$this->headers,'status-one');self::assertSame(409,$status['status']);
        $this->pdo->exec('UPDATE api_v2_project_authorization_state SET authorization_generation=authorization_generation+1 WHERE application_pk=3');$refresh=['commandId'=>'673e4567-e89b-42d3-a456-426614174000','externalId'=>'race','expectedPublicId'=>str_repeat('f',32),'expectedPriorRevision'=>$status['payload']['binding']['revision'],'expectedRevision'=>$status['payload']['resource']['revision'],'expectedProjectionSha256'=>$status['payload']['resource']['projectionSha256'],'expectedAuthorizationGeneration'=>$status['payload']['authorizationGeneration']];$this->assertSyncConflict(api_v2_project_sync_write($this->pdo,'refresh',$refresh,7,$this->headers,'generation-race'),'authorization_generation_conflict','generation-race');
        $status=api_v2_project_binding_status_read($this->pdo,'race',7,$this->headers,'status-two');self::assertSame('2',$status['payload']['authorizationGeneration']);$this->pdo->beginTransaction();$this->pdo->exec("UPDATE projects SET name='Browser edit two' WHERE id=$id");(new ProjectRevisionService($this->pdo))->advance($id,'update');$this->pdo->commit();$refresh['commandId']='683e4567-e89b-42d3-a456-426614174000';$refresh['expectedAuthorizationGeneration']=$status['payload']['authorizationGeneration'];$refresh['expectedRevision']=$status['payload']['resource']['revision'];$refresh['expectedProjectionSha256']=$status['payload']['resource']['projectionSha256'];$this->assertSyncConflict(api_v2_project_sync_write($this->pdo,'refresh',$refresh,7,$this->headers,'revision-race'),'resource_precondition_conflict','revision-race');self::assertSame(1,(int)$this->pdo->query("SELECT project_revision FROM api_v2_project_external_bindings WHERE external_id='race'")->fetchColumn());
    }
    public function testReleaseAttestationFailsClosedAndReceiptGoesStale():void
    {
        $initial=api_v2_project_backfill_attestation($this->pdo);self::assertFalse($initial['complete']);self::assertSame(0,$initial['violations']['index']);self::assertSame(0,$initial['violations']['foreign_key']);$digest=api_v2_project_backfill_attestation_persist($this->pdo);self::assertTrue(api_v2_project_backfill_attestation_receipt_is_current($this->pdo,$digest));self::assertTrue(api_v2_project_backfill_attestation($this->pdo)['complete']);$this->pdo->exec("UPDATE schema_migrations SET filename='wrong.sql' WHERE version=102");$bad=api_v2_project_backfill_attestation($this->pdo);self::assertFalse($bad['schemaReady']);self::assertFalse($bad['complete']);$this->pdo->exec("UPDATE schema_migrations SET filename='0102_api_v2_project_synchronization.sql' WHERE version=102");$this->pdo->exec('DELETE FROM api_v2_project_authorization_state');$missingAuth=api_v2_project_backfill_attestation($this->pdo);self::assertGreaterThan(0,$missingAuth['violations']['authorization']);self::assertFalse($missingAuth['complete']);$this->pdo->exec('INSERT INTO api_v2_project_authorization_state(application_pk,authorization_generation) VALUES(3,0)');$this->pdo->exec("UPDATE schema_migrations SET checksum='".str_repeat('0',64)."' WHERE version=102");self::assertFalse(api_v2_project_backfill_attestation_receipt_is_current($this->pdo,$digest));$this->pdo->exec('DROP TABLE api_v2_project_command_receipts');$partial=api_v2_project_backfill_attestation($this->pdo);self::assertGreaterThan(0,$partial['violations']['schema']);self::assertFalse($partial['complete']);
    }
    public function testMigrationChecksumAcceptsRawLfAndCrLf():void
    {
        $path=tempnam(sys_get_temp_dir(),'pa-release-');self::assertNotFalse($path);try{file_put_contents($path,"one\r\ntwo\r\n");$accepted=api_v2_project_release_file_accepted_digests($path);self::assertContains(hash('sha256',"one\r\ntwo\r\n"),$accepted);self::assertContains(hash('sha256',"one\ntwo\n"),$accepted);self::assertSame(hash('sha256',"one\ntwo\n"),api_v2_project_release_file_digest($path));}finally{@unlink($path);}
    }
    public function testCanonicalParserAndDefaultOffSurface():void
    {
        self::assertNull(api_v2_project_sync_command_parse('bind','{}'));$root=dirname(__DIR__,2);$router=file_get_contents($root.'/public/index.php');self::assertStringContainsString('APP_API_V2_PROJECTS_BINDING_REFRESH_ENABLED',$router);self::assertStringContainsString('APP_API_V2_PROJECTS_CREATE_ENABLED=false',file_get_contents($root.'/config/.env.example'));require_once $root.'/src/utils/api_scopes.php';foreach(['projects.create','projects.write','projects.bind','projects.binding.revision.refresh','projects.binding_status.read','projects.inventory.read']as$scope)self::assertFalse(api_key_has_scope('full',$scope,false));
    }
}
