<?php
declare(strict_types=1);

use App\Services\ProjectRevisionService;
use PHPUnit\Framework\TestCase;

final class ApiV2ProjectSynchronizationTest extends TestCase
{
    private PDO $pdo;private array $headers=['source'=>'123e4567-e89b-42d3-a456-426614174000','application'=>'223e4567-e89b-42d3-a456-426614174000','epoch'=>'323e4567-e89b-42d3-a456-426614174000'];
    protected function setUp():void
    {
        if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped('pdo_sqlite required');$root=dirname(__DIR__,2);require_once $root.'/src/utils/api_v2_project_sync.php';require_once $root.'/src/utils/api_v2_project_release_safety.php';
        $this->pdo=new PDO('sqlite::memory:');$this->pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$this->pdo->exec('PRAGMA foreign_keys=ON');
        $this->pdo->exec("CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY,filename TEXT,checksum TEXT);CREATE TABLE api_keys(id INTEGER PRIMARY KEY,api_v2_application_id INTEGER,revoked_at TEXT);CREATE TABLE api_v2_applications(id INTEGER PRIMARY KEY,application_id TEXT);CREATE TABLE api_v2_history_identity(singleton INTEGER PRIMARY KEY,source_instance_id TEXT,history_epoch TEXT);CREATE TABLE api_v2_project_authorization_state(application_pk INTEGER PRIMARY KEY,authorization_generation INTEGER,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE users(id INTEGER PRIMARY KEY);
        CREATE TABLE organizations(id INTEGER PRIMARY KEY,public_id TEXT,name TEXT,general_email TEXT,general_phone TEXT,address_line1 TEXT,address_line2 TEXT,city TEXT,state TEXT,postal_code TEXT,country TEXT);CREATE TABLE clients(id INTEGER PRIMARY KEY,public_id TEXT,name TEXT,email TEXT,phone TEXT,client_type TEXT,organization_id INTEGER,address_line1 TEXT,address_line2 TEXT,city TEXT,state TEXT,postal_code TEXT,country TEXT);
        CREATE TABLE api_v2_directory_resource_state(resource_type TEXT,public_id TEXT,revision INTEGER,projection_sha256 TEXT,present INTEGER,PRIMARY KEY(resource_type,public_id));CREATE TABLE api_v2_directory_external_bindings(application_pk INTEGER,resource_type TEXT,external_id TEXT,public_id TEXT,resource_revision INTEGER,resource_projection_sha256 TEXT,status TEXT,PRIMARY KEY(application_pk,resource_type,external_id));
        CREATE TABLE projects(id INTEGER PRIMARY KEY AUTOINCREMENT,public_id TEXT UNIQUE,client_id INTEGER,organization_id INTEGER,department_id INTEGER,name TEXT,description TEXT,status TEXT,completed_at TEXT,archived_at TEXT,portal_publish_enabled INTEGER DEFAULT 1,public_project_enabled INTEGER DEFAULT 0,revision INTEGER DEFAULT 1,estimated_start TEXT,estimated_end TEXT,source_version TEXT,invoice_billing_period TEXT,project_invoice_auto_email INTEGER,created_by INTEGER,updated_at TEXT);CREATE TABLE project_retention_guards(project_public_id TEXT PRIMARY KEY);CREATE TABLE project_changes(project_public_id TEXT,revision INTEGER,action_name TEXT,projection_sha256 TEXT,application_pk INTEGER,command_id TEXT,actor_user_id INTEGER,changed_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(project_public_id,revision));
        CREATE TABLE api_v2_project_external_bindings(application_pk INTEGER,external_id TEXT,project_public_id TEXT,project_revision INTEGER,project_projection_sha256 TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(application_pk,external_id),UNIQUE(application_pk,project_public_id));CREATE TABLE api_v2_project_command_receipts(application_pk INTEGER,history_epoch TEXT,command_id TEXT,command_type TEXT,request_sha256 TEXT,external_id TEXT,project_public_id TEXT,expected_revision INTEGER,expected_prior_revision INTEGER,expected_projection_sha256 TEXT,expected_authorization_generation INTEGER,result_revision INTEGER,result_projection_sha256 TEXT,result_authorization_generation INTEGER,result_portal_publish_enabled INTEGER,result_public_project_enabled INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(application_pk,history_epoch,command_id));CREATE TABLE api_v2_project_backfill_attestations(attestation_sha256 TEXT PRIMARY KEY,attestation_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
        CREATE TABLE app_config(organization_id INTEGER,config_key TEXT,config_value TEXT);CREATE TABLE project_service_locations(id INTEGER PRIMARY KEY,project_id INTEGER,service_location_id INTEGER,is_default INTEGER);CREATE TABLE schedule_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,project_id INTEGER,job_id INTEGER,service_location_id INTEGER,title TEXT,starts_at TEXT,ends_at TEXT,timezone TEXT,status TEXT,source_type TEXT,source_id INTEGER,created_by INTEGER,UNIQUE(source_type,source_id),FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL);
        CREATE TABLE portal_integration_profiles(id INTEGER PRIMARY KEY,enabled INTEGER,portal_projection_enabled INTEGER,delivery_enabled INTEGER);CREATE TABLE portal_v2_workspaces(id INTEGER PRIMARY KEY,public_id TEXT,root_type TEXT,root_public_id TEXT,display_name TEXT,source_version TEXT,active INTEGER);CREATE TABLE portal_integration_profile_workspaces(profile_id INTEGER,workspace_id INTEGER,active INTEGER);CREATE TABLE portal_projection_state(integration_profile_id INTEGER,workspace_public_id TEXT,source_generation TEXT,source_sequence INTEGER,last_snapshot_hash TEXT,PRIMARY KEY(integration_profile_id,workspace_public_id));CREATE TABLE portal_projection_outbox(id INTEGER PRIMARY KEY,delivery_id TEXT,delivered_at TEXT,payload_json TEXT);
        INSERT INTO api_keys VALUES(7,3,NULL);INSERT INTO api_v2_applications VALUES(3,'223e4567-e89b-42d3-a456-426614174000');INSERT INTO api_v2_history_identity VALUES(1,'123e4567-e89b-42d3-a456-426614174000','323e4567-e89b-42d3-a456-426614174000');INSERT INTO api_v2_project_authorization_state(application_pk,authorization_generation) VALUES(3,0);INSERT INTO app_config VALUES(0,'portal_authoritative_hooks_enabled','1');INSERT INTO organizations VALUES(10,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','Org',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);INSERT INTO clients VALUES(11,'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','Client',NULL,NULL,'business',10,NULL,NULL,NULL,NULL,NULL,NULL);
        INSERT INTO portal_integration_profiles VALUES(9,1,1,1);INSERT INTO portal_v2_workspaces VALUES(8,'workspace-existing','organization','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','Org','workspace-v1',1);INSERT INTO portal_integration_profile_workspaces VALUES(9,8,1);INSERT INTO portal_projection_state VALUES(9,'workspace-existing','generation-existing',4,'snapshot-existing');INSERT INTO portal_projection_outbox VALUES(6,'delivery-existing','2026-09-01','{\"sentinel\":true}');");
        $migrationPath=$root.'/database/migrations/0102_api_v2_project_synchronization.sql';$this->pdo->prepare('INSERT INTO schema_migrations VALUES(102,?,?)')->execute(['0102_api_v2_project_synchronization.sql',hash_file('sha256',$migrationPath)]);
        foreach([['organization',10,'org-ext'],['client',11,'client-ext']]as[$type,$id,$external]){$table=$type==='organization'?'organizations':'clients';$row=$this->pdo->query("SELECT * FROM $table WHERE id=$id")->fetch(PDO::FETCH_ASSOC);$hash=api_v2_directory_projection_hash($type,$row);$public=$row['public_id'];$this->pdo->prepare('INSERT INTO api_v2_directory_resource_state VALUES(?,?,1,?,1)')->execute([$type,$public,$hash]);$this->pdo->prepare("INSERT INTO api_v2_directory_external_bindings VALUES(3,?,?,?,1,?,'active')")->execute([$type,$external,$public,$hash]);}
    }
    private function relation(string$type):array{$public=$type==='organization'?str_repeat('a',32):str_repeat('b',32);$state=$this->pdo->prepare('SELECT projection_sha256 FROM api_v2_directory_resource_state WHERE resource_type=?');$state->execute([$type]);return['externalId'=>$type==='organization'?'org-ext':'client-ext','expectedPublicId'=>$public,'expectedRevision'=>'1','expectedProjectionSha256'=>$state->fetchColumn()];}
    private function portalState():array{return['workspace'=>$this->pdo->query('SELECT * FROM portal_v2_workspaces ORDER BY id')->fetchAll(PDO::FETCH_ASSOC),'projection'=>$this->pdo->query('SELECT * FROM portal_projection_state ORDER BY integration_profile_id,workspace_public_id')->fetchAll(PDO::FETCH_ASSOC),'outbox'=>$this->pdo->query('SELECT * FROM portal_projection_outbox ORDER BY id')->fetchAll(PDO::FETCH_ASSOC)];}
    private function assertPortalUnchanged(array$before):void{self::assertSame($before,$this->portalState(),'Project synchronization must be portal/delivery neutral.');}
    public function testCreateUpdateNoOpBindAndRefreshNeverProjectOrDeliver():void
    {
        $portal=$this->portalState();$create=['commandId'=>'423e4567-e89b-42d3-a456-426614174000','externalId'=>'project-ext','expectedAuthorizationGeneration'=>'0','project'=>['name'=>'Shared name','description'=>'Safe scope','estimatedStart'=>'2026-09-01','estimatedEnd'=>'2026-09-30'],'organization'=>$this->relation('organization'),'client'=>$this->relation('client')];
        $out=api_v2_project_sync_write($this->pdo,'create',$create,7,$this->headers,'r1');self::assertSame(201,$out['status']);self::assertSame('1',$out['payload']['result']['authorizationGeneration']);self::assertSame(['portalPublished'=>false,'publicLinkEnabled'=>false],$out['payload']['result']['presentation']);self::assertSame(1,(int)$this->pdo->query('SELECT COUNT(*) FROM schedule_entries')->fetchColumn());self::assertNull($this->pdo->query('SELECT created_by FROM schedule_entries')->fetchColumn());self::assertSame(1,(int)$this->pdo->query('SELECT revision FROM projects')->fetchColumn());$createVersion=(string)$this->pdo->query('SELECT source_version FROM projects')->fetchColumn();self::assertMatchesRegularExpression('/^v-[0-9a-f]{32}$/',$createVersion);$this->assertPortalUnchanged($portal);
        self::assertTrue(api_v2_project_sync_write($this->pdo,'create',$create,7,$this->headers,'r2')['payload']['replayed']);$this->assertPortalUnchanged($portal);$changed=$create;$changed['project']['name']='Other';self::assertSame(409,api_v2_project_sync_write($this->pdo,'create',$changed,7,$this->headers,'r3')['status']);
        $resource=$out['payload']['result']['resource'];$update=['commandId'=>'523e4567-e89b-42d3-a456-426614174000','externalId'=>'project-ext','expectedRevision'=>$resource['revision'],'expectedProjectionSha256'=>$resource['projectionSha256'],'expectedAuthorizationGeneration'=>'1','project'=>['name'=>'Shared name','description'=>'Updated','estimatedStart'=>'2026-09-01','estimatedEnd'=>'2026-10-01']];$updated=api_v2_project_sync_write($this->pdo,'update',$update,7,$this->headers,'r4');self::assertSame('2',$updated['payload']['result']['resource']['revision']);$updateVersion=(string)$this->pdo->query('SELECT source_version FROM projects')->fetchColumn();self::assertNotSame($createVersion,$updateVersion);$this->assertPortalUnchanged($portal);
        $unchanged=$update;$unchanged['commandId']='533e4567-e89b-42d3-a456-426614174000';$unchanged['expectedRevision']='2';$unchanged['expectedProjectionSha256']=$updated['payload']['result']['resource']['projectionSha256'];$noOp=api_v2_project_sync_write($this->pdo,'update',$unchanged,7,$this->headers,'r5');self::assertSame('2',$noOp['payload']['result']['resource']['revision']);self::assertSame($updateVersion,$this->pdo->query('SELECT source_version FROM projects')->fetchColumn());self::assertSame(2,(int)$this->pdo->query('SELECT COUNT(*) FROM project_changes')->fetchColumn());$this->assertPortalUnchanged($portal);
        $this->pdo->exec("INSERT INTO projects(public_id,organization_id,name,status,portal_publish_enabled,public_project_enabled,revision,source_version,invoice_billing_period,project_invoice_auto_email) VALUES('cccccccccccccccccccccccccccccccc',10,'Browser project','not_started',1,0,1,'browser-v1','per_invoice',0)");$browserId=(int)$this->pdo->lastInsertId();$this->pdo->beginTransaction();$browser=(new ProjectRevisionService($this->pdo))->initialize($browserId,'baseline');$this->pdo->commit();$bind=['commandId'=>'543e4567-e89b-42d3-a456-426614174000','externalId'=>'browser-project-ext','expectedPublicId'=>str_repeat('c',32),'expectedRevision'=>'1','expectedProjectionSha256'=>ProjectRevisionService::projectionHash($browser),'expectedAuthorizationGeneration'=>'1'];$bound=api_v2_project_sync_write($this->pdo,'bind',$bind,7,$this->headers,'r6');self::assertSame(200,$bound['status']);self::assertSame('2',$bound['payload']['result']['authorizationGeneration']);$this->assertPortalUnchanged($portal);
        $inventory=api_v2_project_inventory_read($this->pdo,null,10,7,$this->headers,'r7');self::assertCount(2,$inventory['projects']);self::assertArrayNotHasKey('budget',$inventory['projects'][0]);$id=(int)$this->pdo->query("SELECT id FROM projects WHERE public_id='".$resource['publicId']."'")->fetchColumn();$this->pdo->beginTransaction();$this->pdo->exec("UPDATE projects SET name='Browser edit' WHERE id=$id");$live=(new ProjectRevisionService($this->pdo))->advance($id,'update');$this->pdo->commit();self::assertSame(409,api_v2_project_binding_status_read($this->pdo,'project-ext',7,$this->headers,'r8')['status']);
        $hash=ProjectRevisionService::projectionHash($live);$refresh=['commandId'=>'623e4567-e89b-42d3-a456-426614174000','externalId'=>'project-ext','expectedPublicId'=>$resource['publicId'],'expectedPriorRevision'=>'2','expectedRevision'=>'3','expectedProjectionSha256'=>$hash,'expectedAuthorizationGeneration'=>'2'];$refreshed=api_v2_project_sync_write($this->pdo,'refresh',$refresh,7,$this->headers,'r9');self::assertSame('3',$refreshed['payload']['result']['authorizationGeneration']);self::assertSame(200,api_v2_project_binding_status_read($this->pdo,'project-ext',7,$this->headers,'r10')['status']);$this->assertPortalUnchanged($portal);
    }
    public function testReleaseAttestationFailsClosedAndReceiptGoesStale():void
    {
        $initial=api_v2_project_backfill_attestation($this->pdo);self::assertFalse($initial['complete']);self::assertSame(0,$initial['violations']['index']);self::assertSame(0,$initial['violations']['foreign_key']);$digest=api_v2_project_backfill_attestation_persist($this->pdo);self::assertTrue(api_v2_project_backfill_attestation_receipt_is_current($this->pdo,$digest));self::assertTrue(api_v2_project_backfill_attestation($this->pdo)['complete']);$this->pdo->exec("UPDATE schema_migrations SET filename='wrong.sql' WHERE version=102");$bad=api_v2_project_backfill_attestation($this->pdo);self::assertFalse($bad['schemaReady']);self::assertFalse($bad['complete']);$this->pdo->exec("UPDATE schema_migrations SET filename='0102_api_v2_project_synchronization.sql' WHERE version=102");$this->pdo->exec('DELETE FROM api_v2_project_authorization_state');$missingAuth=api_v2_project_backfill_attestation($this->pdo);self::assertGreaterThan(0,$missingAuth['violations']['authorization']);self::assertFalse($missingAuth['complete']);$this->pdo->exec('INSERT INTO api_v2_project_authorization_state(application_pk,authorization_generation) VALUES(3,0)');$this->pdo->exec("UPDATE schema_migrations SET checksum='".str_repeat('0',64)."' WHERE version=102");self::assertFalse(api_v2_project_backfill_attestation_receipt_is_current($this->pdo,$digest));$this->pdo->exec('DROP TABLE api_v2_project_command_receipts');$partial=api_v2_project_backfill_attestation($this->pdo);self::assertGreaterThan(0,$partial['violations']['schema']);self::assertFalse($partial['complete']);
    }
    public function testMigrationChecksumAcceptsRawLfAndCrLf():void
    {
        $path=tempnam(sys_get_temp_dir(),'pa-release-');self::assertNotFalse($path);try{file_put_contents($path,"one\r\ntwo\r\n");$accepted=api_v2_project_release_file_accepted_digests($path);self::assertContains(hash('sha256',"one\r\ntwo\r\n"),$accepted);self::assertContains(hash('sha256',"one\ntwo\n"),$accepted);self::assertSame(hash('sha256',"one\ntwo\n"),api_v2_project_release_file_digest($path));}finally{@unlink($path);}
    }
    public function testCanonicalParserAndDefaultOffSurface():void
    {
        self::assertNull(api_v2_project_sync_command_parse('bind','{}'));$root=dirname(__DIR__,2);$router=file_get_contents($root.'/public/index.php');self::assertStringContainsString('APP_API_V2_PROJECTS_BINDING_REFRESH_ENABLED',$router);self::assertStringContainsString('APP_API_V2_PROJECTS_CREATE_ENABLED=false',file_get_contents($root.'/config/.env.example'));require_once $root.'/src/utils/api_scopes.php';foreach(['projects.create','projects.write','projects.bind','projects.binding.revision.refresh','projects.binding_status.read','projects.inventory.read']as$scope)self::assertFalse(api_key_has_scope('full',$scope,false));
    }
}
