<?php
declare(strict_types=1);

use App\Services\ProjectRevisionService;
use PHPUnit\Framework\TestCase;

final class ApiV2ProjectSynchronizationTest extends TestCase
{
    private PDO $pdo;private array $headers=['source'=>'123e4567-e89b-42d3-a456-426614174000','application'=>'223e4567-e89b-42d3-a456-426614174000','epoch'=>'323e4567-e89b-42d3-a456-426614174000'];
    protected function setUp():void
    {
        if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped('pdo_sqlite required');require_once dirname(__DIR__,2).'/src/utils/api_v2_project_sync.php';
        $this->pdo=new PDO('sqlite::memory:');$this->pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
        $this->pdo->exec("CREATE TABLE api_keys(id INTEGER PRIMARY KEY,api_v2_application_id INTEGER,revoked_at TEXT);CREATE TABLE api_v2_applications(id INTEGER PRIMARY KEY,application_id TEXT);CREATE TABLE api_v2_history_identity(singleton INTEGER PRIMARY KEY,source_instance_id TEXT,history_epoch TEXT);CREATE TABLE api_v2_project_authorization_state(application_pk INTEGER PRIMARY KEY,authorization_generation INTEGER);
        CREATE TABLE organizations(id INTEGER PRIMARY KEY,public_id TEXT,name TEXT,general_email TEXT,general_phone TEXT,address_line1 TEXT,address_line2 TEXT,city TEXT,state TEXT,postal_code TEXT,country TEXT);
        CREATE TABLE clients(id INTEGER PRIMARY KEY,public_id TEXT,name TEXT,email TEXT,phone TEXT,client_type TEXT,organization_id INTEGER,address_line1 TEXT,address_line2 TEXT,city TEXT,state TEXT,postal_code TEXT,country TEXT);
        CREATE TABLE api_v2_directory_resource_state(resource_type TEXT,public_id TEXT,revision INTEGER,projection_sha256 TEXT,present INTEGER,PRIMARY KEY(resource_type,public_id));
        CREATE TABLE api_v2_directory_external_bindings(application_pk INTEGER,resource_type TEXT,external_id TEXT,public_id TEXT,resource_revision INTEGER,resource_projection_sha256 TEXT,status TEXT,PRIMARY KEY(application_pk,resource_type,external_id));
        CREATE TABLE projects(id INTEGER PRIMARY KEY AUTOINCREMENT,public_id TEXT UNIQUE,client_id INTEGER,organization_id INTEGER,department_id INTEGER,name TEXT,description TEXT,status TEXT,completed_at TEXT,archived_at TEXT,portal_publish_enabled INTEGER DEFAULT 1,public_project_enabled INTEGER DEFAULT 0,revision INTEGER DEFAULT 1,estimated_start TEXT,estimated_end TEXT,source_version TEXT,invoice_billing_period TEXT,project_invoice_auto_email INTEGER,created_by INTEGER,updated_at TEXT);
        CREATE TABLE project_retention_guards(project_public_id TEXT PRIMARY KEY);CREATE TABLE project_changes(project_public_id TEXT,revision INTEGER,action_name TEXT,projection_sha256 TEXT,application_pk INTEGER,command_id TEXT,actor_user_id INTEGER,changed_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(project_public_id,revision));
        CREATE TABLE api_v2_project_external_bindings(application_pk INTEGER,external_id TEXT,project_public_id TEXT,project_revision INTEGER,project_projection_sha256 TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(application_pk,external_id),UNIQUE(application_pk,project_public_id));
        CREATE TABLE api_v2_project_command_receipts(application_pk INTEGER,history_epoch TEXT,command_id TEXT,command_type TEXT,request_sha256 TEXT,external_id TEXT,project_public_id TEXT,expected_revision INTEGER,expected_prior_revision INTEGER,expected_projection_sha256 TEXT,expected_authorization_generation INTEGER,result_revision INTEGER,result_projection_sha256 TEXT,result_authorization_generation INTEGER,result_portal_publish_enabled INTEGER,result_public_project_enabled INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(application_pk,history_epoch,command_id));CREATE TABLE api_v2_project_backfill_attestations(attestation_sha256 TEXT PRIMARY KEY,attestation_json TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
        CREATE TABLE app_config(organization_id INTEGER,config_key TEXT,config_value TEXT);CREATE TABLE project_service_locations(id INTEGER PRIMARY KEY,project_id INTEGER,service_location_id INTEGER,is_default INTEGER);CREATE TABLE schedule_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,project_id INTEGER,job_id INTEGER,service_location_id INTEGER,title TEXT,starts_at TEXT,ends_at TEXT,timezone TEXT,status TEXT,source_type TEXT,source_id INTEGER,created_by INTEGER,UNIQUE(source_type,source_id));
        INSERT INTO api_keys VALUES(7,3,NULL);INSERT INTO api_v2_applications VALUES(3,'223e4567-e89b-42d3-a456-426614174000');INSERT INTO api_v2_history_identity VALUES(1,'123e4567-e89b-42d3-a456-426614174000','323e4567-e89b-42d3-a456-426614174000');INSERT INTO api_v2_project_authorization_state VALUES(3,0);INSERT INTO app_config VALUES(0,'portal_authoritative_hooks_enabled','0');
        INSERT INTO organizations VALUES(10,'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa','Org',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);INSERT INTO clients VALUES(11,'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb','Client',NULL,NULL,'business',10,NULL,NULL,NULL,NULL,NULL,NULL);");
        foreach([['organization',10,'org-ext'],['client',11,'client-ext']]as[$type,$id,$external]){$table=$type==='organization'?'organizations':'clients';$row=$this->pdo->query("SELECT * FROM $table WHERE id=$id")->fetch(PDO::FETCH_ASSOC);$hash=api_v2_directory_projection_hash($type,$row);$public=$row['public_id'];$this->pdo->prepare('INSERT INTO api_v2_directory_resource_state VALUES(?,?,1,?,1)')->execute([$type,$public,$hash]);$this->pdo->prepare("INSERT INTO api_v2_directory_external_bindings VALUES(3,?,?,?,1,?,'active')")->execute([$type,$external,$public,$hash]);}
    }
    private function relation(string$type):array{$public=$type==='organization'?str_repeat('a',32):str_repeat('b',32);$state=$this->pdo->prepare('SELECT projection_sha256 FROM api_v2_directory_resource_state WHERE resource_type=?');$state->execute([$type]);return['externalId'=>$type==='organization'?'org-ext':'client-ext','expectedPublicId'=>$public,'expectedRevision'=>'1','expectedProjectionSha256'=>$state->fetchColumn()];}
    public function testCreateUpdateInventoryReplayAndRefreshAreFenced():void
    {
        $create=['commandId'=>'423e4567-e89b-42d3-a456-426614174000','externalId'=>'project-ext','expectedAuthorizationGeneration'=>'0','project'=>['name'=>'Shared name','description'=>'Safe scope','estimatedStart'=>'2026-09-01','estimatedEnd'=>'2026-09-30'],'organization'=>$this->relation('organization'),'client'=>$this->relation('client')];
        $out=api_v2_project_sync_write($this->pdo,'create',$create,7,$this->headers,'r1');self::assertSame(201,$out['status']);self::assertSame('1',$out['payload']['result']['authorizationGeneration']);self::assertSame(['portalPublished'=>false,'publicLinkEnabled'=>false],$out['payload']['result']['presentation']);self::assertSame(10,(int)$this->pdo->query('SELECT organization_id FROM projects')->fetchColumn());self::assertSame(1,(int)$this->pdo->query('SELECT COUNT(*) FROM schedule_entries')->fetchColumn());
        self::assertTrue(api_v2_project_sync_write($this->pdo,'create',$create,7,$this->headers,'r2')['payload']['replayed']);$changed=$create;$changed['project']['name']='Other';self::assertSame(409,api_v2_project_sync_write($this->pdo,'create',$changed,7,$this->headers,'r3')['status']);
        $resource=$out['payload']['result']['resource'];$update=['commandId'=>'523e4567-e89b-42d3-a456-426614174000','externalId'=>'project-ext','expectedRevision'=>$resource['revision'],'expectedProjectionSha256'=>$resource['projectionSha256'],'expectedAuthorizationGeneration'=>'1','project'=>['name'=>'Shared name','description'=>'Updated','estimatedStart'=>'2026-09-01','estimatedEnd'=>'2026-10-01']];$updated=api_v2_project_sync_write($this->pdo,'update',$update,7,$this->headers,'r4');self::assertSame('2',$updated['payload']['result']['resource']['revision']);
        $inventory=api_v2_project_inventory_read($this->pdo,null,1,7,$this->headers,'r5');self::assertCount(1,$inventory['projects']);self::assertArrayNotHasKey('budget',$inventory['projects'][0]);
        $id=(int)$this->pdo->query('SELECT id FROM projects')->fetchColumn();$this->pdo->beginTransaction();$this->pdo->exec("UPDATE projects SET name='Browser edit' WHERE id=$id");$live=(new ProjectRevisionService($this->pdo))->advance($id,'update');$this->pdo->commit();self::assertSame(409,api_v2_project_binding_status_read($this->pdo,'project-ext',7,$this->headers,'r6')['status']);
        $hash=ProjectRevisionService::projectionHash($live);$refresh=['commandId'=>'623e4567-e89b-42d3-a456-426614174000','externalId'=>'project-ext','expectedPublicId'=>$resource['publicId'],'expectedPriorRevision'=>'2','expectedRevision'=>'3','expectedProjectionSha256'=>$hash,'expectedAuthorizationGeneration'=>'1'];$refreshed=api_v2_project_sync_write($this->pdo,'refresh',$refresh,7,$this->headers,'r7');self::assertSame('2',$refreshed['payload']['result']['authorizationGeneration']);self::assertSame(200,api_v2_project_binding_status_read($this->pdo,'project-ext',7,$this->headers,'r8')['status']);require_once dirname(__DIR__,2).'/src/utils/api_v2_project_release_safety.php';$proof=api_v2_project_backfill_attestation($this->pdo);self::assertTrue($proof['complete']);self::assertMatchesRegularExpression('/^[0-9a-f]{64}$/',api_v2_project_backfill_attestation_persist($this->pdo));
    }
    public function testCanonicalParserAndDefaultOffSurface():void
    {
        self::assertNull(api_v2_project_sync_command_parse('bind','{}'));$root=dirname(__DIR__,2);$router=file_get_contents($root.'/public/index.php');self::assertStringContainsString('APP_API_V2_PROJECTS_BINDING_REFRESH_ENABLED',$router);self::assertStringContainsString('APP_API_V2_PROJECTS_CREATE_ENABLED=false',file_get_contents($root.'/config/.env.example'));require_once $root.'/src/utils/api_scopes.php';foreach(['projects.create','projects.write','projects.bind','projects.binding.revision.refresh','projects.binding_status.read','projects.inventory.read']as$scope)self::assertFalse(api_key_has_scope('full',$scope,false));
    }
}
